[package]
name = "swc_plugin_simple_transform_macro_props"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
convert_case = "0.6.0"
serde = "1"
serde_json = "1.0.79"
swc_common = { version = "0.36.0", features = ["concurrent"] }
swc_core = { version = "0.99.2", features = ["ecma_quote", "ecma_plugin_transform"] }
swc_ecma_ast = "0.117.0"
swc_ecma_utils = "0.133.1"
swc_ecma_visit = "0.103.1"
swc_plugin_macro = "0.9.16"
swc_plugin_proxy = "0.46.0"
tracing = { version = "0.1.37", features = ["release_max_level_off"] }

[dev-dependencies]
testing = "0.38.0"
swc_ecma_parser = "0.148.0"
swc_ecma_transforms_react = "0.189.0"
swc_ecma_transforms_testing = "0.146.0"
